/*  Even Fibonacci Numbers
    **********************

    Problem 2:
    ----------
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


#include <iostream>

int main() {
    
    int a {1}, b {2}, sum {}, temp {};

    while (a < 4e6) {
    
        if (a % 2 == 0) {
            sum += a;
        }
    
        // find next term in the sequence
        temp = a;
        a = b;
        b += temp;        
    }
    
    std::cout << "Sum = " << sum << std::endl;
    
    return 0;
}